export const FETCH_MOVIES = "FETCH_MOVIES"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED"

export const FETCH_MOVIE = "FETCH_MOVIE"
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS"
export const FETCH_MOVIE_FAILED = "FETCH_MOVIE_FAILED"


export const SET_SEARCH = "SET_SEARCH"
export const SET_SEARCH_SUCCESS = "SET_SEARCH_SUCCESS"

export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE"
export const SET_SELECTED_MOVIE_SUCCESS = "SET_SELECTED_MOVIE_SUCCESS"